/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  aws_project_region: 'us-east-1',
  aws_cognito_region: 'us-east-1', 
  aws_user_pools_id: 'us-east-1_0BnGQZ2AO', 
  aws_user_pools_web_client_id: '7357poqc90amf4c1c7t3i6dqjs',
  aws_mandatory_sign_in: false,
};




export default config;
