/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_0BnGQZ2AO",
        "userPoolWebClientId": "7357poqc90amf4c1c7t3i6dqjs",
        "mandatorySignIn": false
    }
};




export default awsmobile;
